services:
  - type: web
    name: plus-api
    runtime: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
